export default {
  data: [],
  banner: [],
  goodSale: [],
  goodsNew: [],
  goodsPopular: [],
  mainTopic: [],
  cateList: [],
  fenleiList: [],
  topicBanner: [],
  column: [],
  recommend:[],
  zhenpin:[],
  tenfifteen:[],
  yxLook:{},
  findMore:[],
}
